### ISSUE TITLE
PHP Gasp documentation ?

### ISSUE THREAD

**Issue by buxx** [troelsfr/Gasp#1]
I come from Breathe and i have trouble with PHP doc generation (see [here](https://github.com/michaeljones/breathe/issues/217)). Do i will have same trouble with Gasp ?

**Comment by troels-im** [comment]
I am actually not sure whether it will work with PHP since I only used it for C++. It can be that it will work, but the only way to find out is to try.

**Comment by buxx** [comment]
After try, it don't look like working.

**Comment by troels-im** [comment]
Do you have a minimal examples that reproduce the problem? I cannot promise
that I will be able to fix it since I have very limited time, but I can
give it a go if you could give an example of what you want to do and what
does not work.

Best,
Troels

**Comment by buxx** [comment]
Hi :)
I created test project: https://github.com/buxx/gasp-test 
Sphinx conf.py is here: https://github.com/buxx/gasp-test/blob/master/doc/source/conf.py (`doxygen_xml` is hardcoded, think to update)
To build i use (in `doc` folder) `rm -rf build/* && make html`
Regards,
Bux.

**Comment by troels-im** [comment]
Hi again,

There are two reasons why your attempt to use Gasp fails:

1) Doxygen apparently uses backslash to indicate name spaces in PHP. This
is different from C++ and hence, therefore Gasp does not work. However, it
can be fixed with one line of code.

I have pushed an update that fixes this.

2) Admittingly the documentation of Gasp is close to being non-existent, so
my apologies on that part.

Your index.rst should look like this:

# Welcome to TestProject's documentation!

Contents:

.. toctree::
   :maxdepth: 2

.. doxygen:: class/members
   Test::Dog
   :public:
   :private:
   :all:

# Indices and tables
- :ref:`genindex`
- :ref:`modindex`
- :ref:`search`

Note the extra colon after doxygen. The first argument is the html template
from which the documentation will be rendered. The second line is the class
or scope you want documented. The three next lines states that it should
make documentation for public and private members, and all means that it
should include functions with no brief documentation, You also have a few
other options such as primary that tells the Gasp that this is the primary
location of the documentation. Finally, you have a separate HTML class
called synopsis.

Please try it out and let me know if this solves your problem. Attached you
see what the build looks like on my machine.

Best,
Troels

**Comment by troels-im** [comment]
PS: You can also add a synopsis like this:

# Dog class overview

.. doxygen:: class/synopsis
   Test::Dog
   :public:
   :private:
   :all:

Blah blah blah

# Dog class details

.. doxygen:: class/members
   Test::Dog
   :public:
   :private:
   :all:

It automatically links the synopsis to the details description and they
need not to be on the same page (if I remember correctly). Finally you can
change the files in gasp/templates/class/\* to make the appearance beautiful.

Troels

**Comment by buxx** [comment]
Thank's for it !
I pull your update and update my [index.rst](https://raw.githubusercontent.com/buxx/gasp-test/master/doc/source/index.rst) file. But i've an error:

```
➜  doc git:(master) rm -rf build/* && make html   
zsh: sure you want to delete all the files in /home/bsevajol/projects/tests/gasp-test/doc/build [yn]? y
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                                    
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
Loading Doxygen documentation ...                                                                                                                                                  
Generating Doxygen output
WARNING: could not find 'Test::Dog'
Filename:  class/synopsis
XML Path:  /home/bsevajol/projects/tests/breathe-test/doc/xml/

Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
UndefinedError: 'objects' is undefined
The full traceback has been saved in /tmp/sphinx-err-69Yxdk.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Erreur 1
➜  doc git:(master) cat /tmp/sphinx-err-69Yxdk.log
# Sphinx version: 1.3.1
# Python version: 2.7.6 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [100%] index
# Loaded extensions:
#   gasp (unknown version) from /usr/lib/python2.7/dist-packages/gasp/__init__.py
#   alabaster (0.7.6) from /usr/local/lib/python2.7/dist-packages/alabaster/__init__.pyc
#   sphinxcontrib.phpdomain (unknown version) from /usr/local/lib/python2.7/dist-packages/sphinxcontrib/phpdomain.pyc
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 316, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 354, in write
    self._write_serial(sorted(docnames), warnings)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/builders/__init__.py", line 360, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1291, in get_and_resolve_doctree
    self.resolve_references(doctree, docname, builder)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/environment.py", line 1570, in resolve_references
    builder.app.emit('doctree-resolved', doctree, fromdocname)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/usr/lib/python2.7/dist-packages/gasp/__init__.py", line 278, in process_doxygen
    node.render()
  File "/usr/lib/python2.7/dist-packages/gasp/__init__.py", line 81, in render
    return template.render(**self.context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/gasp/templates/class/synopsis.html", line 2, in top-level template code
    {% set class = objects[0] %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 389, in getitem
    return obj[argument]
UndefinedError: 'objects' is undefined
```

You said "Attached you see what the build looks like on my machine", where can i found this attachemnt ?

Thank's !

**Comment by buxx** [comment]
I note ```WARNING: could not find 'Test::Dog'``` must be the problem. Main error in jinja2 is consequence i think.

**Comment by buxx** [comment]
(Note: I delete previous messages, my conf.py was wrong ...)
Perfect ! Your update and instructions are working !
Thank for this :)

**Comment by troels-im** [comment]
Happy to help :)

Troels
